import pluginRegexp from 'eslint-plugin-regexp'

/**
 * @module cardinal/quality/regex
 * @summary Reglas para validación y optimización de expresiones regulares.
 * @remarks Basado en eslint-plugin-regexp para detectar problemas y mejorar regex.
 */

export default {
  name: 'cardinal/quality/regex',
  plugins: {
    regex: pluginRegexp,
  },
  rules: {
    'regex/confusing-quantifier': 'error',
    'regex/control-character-escape': 'error',
    'regex/grapheme-string-literal': 'off',
    'regex/hexadecimal-escape': 'off',
    'regex/letter-case': 'off',
    'regex/match-any': 'error',
    'regex/negation': 'error',
    'regex/no-contradiction-with-assertion': 'error',
    'regex/no-control-character': 'error',
    'regex/no-dupe-characters-character-class': 'error',
    'regex/no-dupe-disjunctions': 'error',
    'regex/no-empty-alternative': 'error',
    'regex/no-empty-capturing-group': 'error',
    'regex/no-empty-character-class': 'error',
    'regex/no-empty-group': 'error',
    'regex/no-empty-lookarounds-assertion': 'error',
    'regex/no-empty-string-literal': 'error',
    'regex/no-escape-backspace': 'error',
    'regex/no-extra-lookaround-assertions': 'error',
    'regex/no-invalid-regexp': 'error',
    'regex/no-invisible-character': 'error',
    'regex/no-lazy-ends': 'error',
    'regex/no-legacy-features': 'error',
    'regex/no-misleading-capturing-group': 'error',
    'regex/no-misleading-unicode-character': 'error',
    'regex/no-missing-g-flag': 'error',
    'regex/no-non-standard-flag': 'error',
    'regex/no-obscure-range': 'error',
    'regex/no-octal': 'error',
    'regex/no-optional-assertion': 'error',
    'regex/no-potentially-useless-backreference': 'error',
    'regex/no-standalone-backslash': 'error',
    'regex/no-super-linear-backtracking': 'error',
    'regex/no-super-linear-move': 'error',
    'regex/no-trivially-nested-assertion': 'error',
    'regex/no-trivially-nested-quantifier': 'error',
    'regex/no-unused-capturing-group': 'warn',
    'regex/no-useless-assertions': 'error',
    'regex/no-useless-backreference': 'error',
    'regex/no-useless-character-class': 'error',
    'regex/no-useless-dollar-replacements': 'error',
    'regex/no-useless-escape': 'error',
    'regex/no-useless-flag': 'error',
    'regex/no-useless-lazy': 'error',
    'regex/no-useless-non-capturing-group': 'error',
    'regex/no-useless-quantifier': 'error',
    'regex/no-useless-range': 'error',
    'regex/no-useless-set-operand': 'error',
    'regex/no-useless-string-literal': 'error',
    'regex/no-useless-two-nums-quantifier': 'error',
    'regex/no-zero-quantifier': 'error',
    'regex/optimal-lookaround-quantifier': 'error',
    'regex/optimal-quantifier-concatenation': 'error',
    'regex/prefer-character-class': 'error',
    'regex/prefer-d': 'error',
    'regex/prefer-escape-replacement-dollar-char': 'error',
    'regex/prefer-lookaround': 'off',
    'regex/prefer-named-backreference': 'off',
    'regex/prefer-named-capture-group': 'off',
    'regex/prefer-named-replacement': 'off',
    'regex/prefer-plus-quantifier': 'error',
    'regex/prefer-predefined-assertion': 'error',
    'regex/prefer-quantifier': 'error',
    'regex/prefer-question-quantifier': 'error',
    'regex/prefer-range': 'error',
    'regex/prefer-regexp-exec': 'error',
    'regex/prefer-regexp-test': 'error',
    'regex/prefer-result-array-groups': 'off',
    'regex/prefer-set-operation': 'error',
    'regex/prefer-star-quantifier': 'error',
    'regex/prefer-unicode-codepoint-escapes': 'off',
    'regex/prefer-w': 'error',
    'regex/require-unicode-regexp': 'off',
    'regex/require-unicode-sets-regexp': 'off',
    'regex/simplify-set-operations': 'error',
    'regex/sort-alternatives': 'off',
    'regex/sort-character-class-elements': 'off',
    'regex/sort-flags': 'off',
    'regex/strict': 'off',
    'regex/unicode-escape': 'off',
    'regex/unicode-property': 'off',
    'regex/use-ignore-case': 'error',
  },
}
